common: &common
  username: '<username>'
  password: '<password>'
  security_token: '<security_token>'
  client_id: '<client_id>'
  client_secret: '<client_secret>'
#  host: 'test.salesforce.com'

# You can connect to sandbox orgs by specifying a host. The default host is 'login.salesforce.com'
# Developer Edition accounts do not have access to Sandbox (test.salesforce.com).
# Sandbox is available depending on which edition you have.

test:
  <<: *common

development:
  <<: *common

feature:
  <<: *common

qa:
  <<: *common

production:
  <<: *common