# db_field_name: sf_field_name
salesforce_id: Id
company: Company
first_name: FirstName
last_name: LastName
email: Email
phone: Phone
status: Status
#city: City
#state: State
#country: Country
#zipcode: PostalCode
